package me.zheteng.cbreader.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.zheteng.cbreader.data.FavoriteNewsContent;

import me.zheteng.cbreader.data.FavoriteNewsContentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoriteNewsContentDaoConfig;

    private final FavoriteNewsContentDao favoriteNewsContentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteNewsContentDaoConfig = daoConfigMap.get(FavoriteNewsContentDao.class).clone();
        favoriteNewsContentDaoConfig.initIdentityScope(type);

        favoriteNewsContentDao = new FavoriteNewsContentDao(favoriteNewsContentDaoConfig, this);

        registerDao(FavoriteNewsContent.class, favoriteNewsContentDao);
    }
    
    public void clear() {
        favoriteNewsContentDaoConfig.getIdentityScope().clear();
    }

    public FavoriteNewsContentDao getFavoriteNewsContentDao() {
        return favoriteNewsContentDao;
    }

}
