package me.zheteng.cbreader.data;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import me.zheteng.cbreader.data.FavoriteNewsContent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FAVORITE_NEWS_CONTENT.
*/
public class FavoriteNewsContentDao extends AbstractDao<FavoriteNewsContent, Long> {

    public static final String TABLENAME = "FAVORITE_NEWS_CONTENT";

    /**
     * Properties of entity FavoriteNewsContent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sid = new Property(1, String.class, "sid", false, "SID");
        public final static Property Catid = new Property(2, String.class, "catid", false, "CATID");
        public final static Property Topic = new Property(3, String.class, "topic", false, "TOPIC");
        public final static Property Aid = new Property(4, String.class, "aid", false, "AID");
        public final static Property Title = new Property(5, String.class, "title", false, "TITLE");
        public final static Property Keywords = new Property(6, String.class, "keywords", false, "KEYWORDS");
        public final static Property Hometext = new Property(7, String.class, "hometext", false, "HOMETEXT");
        public final static Property Listorder = new Property(8, String.class, "listorder", false, "LISTORDER");
        public final static Property Comments = new Property(9, String.class, "comments", false, "COMMENTS");
        public final static Property Counter = new Property(10, String.class, "counter", false, "COUNTER");
        public final static Property Mview = new Property(11, String.class, "mview", false, "MVIEW");
        public final static Property Collectnum = new Property(12, String.class, "collectnum", false, "COLLECTNUM");
        public final static Property Good = new Property(13, String.class, "good", false, "GOOD");
        public final static Property Bad = new Property(14, String.class, "bad", false, "BAD");
        public final static Property Score = new Property(15, String.class, "score", false, "SCORE");
        public final static Property Ratings = new Property(16, String.class, "ratings", false, "RATINGS");
        public final static Property Score_story = new Property(17, String.class, "score_story", false, "SCORE_STORY");
        public final static Property Ratings_story = new Property(18, String.class, "ratings_story", false, "RATINGS_STORY");
        public final static Property Pollid = new Property(19, String.class, "pollid", false, "POLLID");
        public final static Property Queueid = new Property(20, String.class, "queueid", false, "QUEUEID");
        public final static Property Ifcom = new Property(21, String.class, "ifcom", false, "IFCOM");
        public final static Property Ishome = new Property(22, String.class, "ishome", false, "ISHOME");
        public final static Property Elite = new Property(23, String.class, "elite", false, "ELITE");
        public final static Property Status = new Property(24, String.class, "status", false, "STATUS");
        public final static Property Inputtime = new Property(25, String.class, "inputtime", false, "INPUTTIME");
        public final static Property Updatetime = new Property(26, String.class, "updatetime", false, "UPDATETIME");
        public final static Property Thumb = new Property(27, String.class, "thumb", false, "THUMB");
        public final static Property Source = new Property(28, String.class, "source", false, "SOURCE");
        public final static Property Data_id = new Property(29, String.class, "data_id", false, "DATA_ID");
        public final static Property Bodytext = new Property(30, String.class, "bodytext", false, "BODYTEXT");
        public final static Property Relation = new Property(31, String.class, "relation", false, "RELATION");
        public final static Property Shorttitle = new Property(32, String.class, "shorttitle", false, "SHORTTITLE");
        public final static Property Brief = new Property(33, String.class, "brief", false, "BRIEF");
        public final static Property Time = new Property(34, String.class, "time", false, "TIME");
    };


    public FavoriteNewsContentDao(DaoConfig config) {
        super(config);
    }
    
    public FavoriteNewsContentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FAVORITE_NEWS_CONTENT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SID' TEXT NOT NULL ," + // 1: sid
                "'CATID' TEXT," + // 2: catid
                "'TOPIC' TEXT," + // 3: topic
                "'AID' TEXT," + // 4: aid
                "'TITLE' TEXT," + // 5: title
                "'KEYWORDS' TEXT," + // 6: keywords
                "'HOMETEXT' TEXT," + // 7: hometext
                "'LISTORDER' TEXT," + // 8: listorder
                "'COMMENTS' TEXT," + // 9: comments
                "'COUNTER' TEXT," + // 10: counter
                "'MVIEW' TEXT," + // 11: mview
                "'COLLECTNUM' TEXT," + // 12: collectnum
                "'GOOD' TEXT," + // 13: good
                "'BAD' TEXT," + // 14: bad
                "'SCORE' TEXT," + // 15: score
                "'RATINGS' TEXT," + // 16: ratings
                "'SCORE_STORY' TEXT," + // 17: score_story
                "'RATINGS_STORY' TEXT," + // 18: ratings_story
                "'POLLID' TEXT," + // 19: pollid
                "'QUEUEID' TEXT," + // 20: queueid
                "'IFCOM' TEXT," + // 21: ifcom
                "'ISHOME' TEXT," + // 22: ishome
                "'ELITE' TEXT," + // 23: elite
                "'STATUS' TEXT," + // 24: status
                "'INPUTTIME' TEXT," + // 25: inputtime
                "'UPDATETIME' TEXT," + // 26: updatetime
                "'THUMB' TEXT," + // 27: thumb
                "'SOURCE' TEXT," + // 28: source
                "'DATA_ID' TEXT," + // 29: data_id
                "'BODYTEXT' TEXT," + // 30: bodytext
                "'RELATION' TEXT," + // 31: relation
                "'SHORTTITLE' TEXT," + // 32: shorttitle
                "'BRIEF' TEXT," + // 33: brief
                "'TIME' TEXT);"); // 34: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FAVORITE_NEWS_CONTENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FavoriteNewsContent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getSid());
 
        String catid = entity.getCatid();
        if (catid != null) {
            stmt.bindString(3, catid);
        }
 
        String topic = entity.getTopic();
        if (topic != null) {
            stmt.bindString(4, topic);
        }
 
        String aid = entity.getAid();
        if (aid != null) {
            stmt.bindString(5, aid);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
 
        String keywords = entity.getKeywords();
        if (keywords != null) {
            stmt.bindString(7, keywords);
        }
 
        String hometext = entity.getHometext();
        if (hometext != null) {
            stmt.bindString(8, hometext);
        }
 
        String listorder = entity.getListorder();
        if (listorder != null) {
            stmt.bindString(9, listorder);
        }
 
        String comments = entity.getComments();
        if (comments != null) {
            stmt.bindString(10, comments);
        }
 
        String counter = entity.getCounter();
        if (counter != null) {
            stmt.bindString(11, counter);
        }
 
        String mview = entity.getMview();
        if (mview != null) {
            stmt.bindString(12, mview);
        }
 
        String collectnum = entity.getCollectnum();
        if (collectnum != null) {
            stmt.bindString(13, collectnum);
        }
 
        String good = entity.getGood();
        if (good != null) {
            stmt.bindString(14, good);
        }
 
        String bad = entity.getBad();
        if (bad != null) {
            stmt.bindString(15, bad);
        }
 
        String score = entity.getScore();
        if (score != null) {
            stmt.bindString(16, score);
        }
 
        String ratings = entity.getRatings();
        if (ratings != null) {
            stmt.bindString(17, ratings);
        }
 
        String score_story = entity.getScore_story();
        if (score_story != null) {
            stmt.bindString(18, score_story);
        }
 
        String ratings_story = entity.getRatings_story();
        if (ratings_story != null) {
            stmt.bindString(19, ratings_story);
        }
 
        String pollid = entity.getPollid();
        if (pollid != null) {
            stmt.bindString(20, pollid);
        }
 
        String queueid = entity.getQueueid();
        if (queueid != null) {
            stmt.bindString(21, queueid);
        }
 
        String ifcom = entity.getIfcom();
        if (ifcom != null) {
            stmt.bindString(22, ifcom);
        }
 
        String ishome = entity.getIshome();
        if (ishome != null) {
            stmt.bindString(23, ishome);
        }
 
        String elite = entity.getElite();
        if (elite != null) {
            stmt.bindString(24, elite);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(25, status);
        }
 
        String inputtime = entity.getInputtime();
        if (inputtime != null) {
            stmt.bindString(26, inputtime);
        }
 
        String updatetime = entity.getUpdatetime();
        if (updatetime != null) {
            stmt.bindString(27, updatetime);
        }
 
        String thumb = entity.getThumb();
        if (thumb != null) {
            stmt.bindString(28, thumb);
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(29, source);
        }
 
        String data_id = entity.getData_id();
        if (data_id != null) {
            stmt.bindString(30, data_id);
        }
 
        String bodytext = entity.getBodytext();
        if (bodytext != null) {
            stmt.bindString(31, bodytext);
        }
 
        String relation = entity.getRelation();
        if (relation != null) {
            stmt.bindString(32, relation);
        }
 
        String shorttitle = entity.getShorttitle();
        if (shorttitle != null) {
            stmt.bindString(33, shorttitle);
        }
 
        String brief = entity.getBrief();
        if (brief != null) {
            stmt.bindString(34, brief);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(35, time);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FavoriteNewsContent readEntity(Cursor cursor, int offset) {
        FavoriteNewsContent entity = new FavoriteNewsContent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // sid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // catid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // topic
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // aid
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // title
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // keywords
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // hometext
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // listorder
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // comments
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // counter
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // mview
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // collectnum
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // good
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // bad
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // score
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // ratings
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // score_story
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // ratings_story
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // pollid
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // queueid
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // ifcom
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // ishome
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // elite
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // status
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // inputtime
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // updatetime
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // thumb
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // source
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // data_id
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // bodytext
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // relation
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // shorttitle
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // brief
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34) // time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FavoriteNewsContent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSid(cursor.getString(offset + 1));
        entity.setCatid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTopic(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAid(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTitle(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setKeywords(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setHometext(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setListorder(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setComments(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCounter(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setMview(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setCollectnum(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setGood(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setBad(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setScore(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setRatings(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setScore_story(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setRatings_story(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setPollid(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setQueueid(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setIfcom(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setIshome(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setElite(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setStatus(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setInputtime(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setUpdatetime(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setThumb(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setSource(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setData_id(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setBodytext(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setRelation(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setShorttitle(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setBrief(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setTime(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FavoriteNewsContent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FavoriteNewsContent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
